#
# {license_notice}
#
# @category    Magento
# @package     Mage_SystemConfiguration
# @subpackage  functional_tests
# @copyright   {copyright}
# @license     {license_link}
#
---
#Manage System Configuration

# 'System Configuration' page
system_configuration:
    uimap: &system_configuration_uimap
        form:
            tabs:
                -
                    customers_customer_configuration:
                        fieldsets:
                            -
                                password_options:
                                    dropdowns:
                                        remind_email_template: //select[@name='groups[password][fields][remind_email_template][value]']
                                    fields:
                                        recovery_link_exp_period: //input[@name='groups[password][fields][reset_link_expiration_period][value]']
                            -
                                captcha:
                                    fields:
                                        captcha_number_of_attempts: //*[@id='customer_captcha_failed_attempts_login']            
                -
                    sales_payment_methods:
                        fieldsets:
                            -
                                banktransfer_payment:
                                    xpath: //fieldset[@id='payment_banktransfer']
                                    links:
                                        bank_transfer_payment_link: //parent::div//a[@id='payment_banktransfer-head']
                                    fields:
                                        btp_title: //input[@name='groups[banktransfer][fields][title][value]']
                                        btp_instruction: //textarea[@name='groups[banktransfer][fields][instructions][value]']
                                        btp_minimum_order_total: //input[@name='groups[banktransfer][fields][min_order_total][value]']
                                        btp_maximum_order_total: //input[@name='groups[banktransfer][fields][max_order_total][value]']
                                        btp_sort_order: //input[@name='groups[banktransfer][fields][sort_order][value]']
                                    dropdowns:
                                        btp_enabled: //select[@name='groups[banktransfer][fields][active][value]']
                                        btp_new_order_status: //select[@name='groups[banktransfer][fields][order_status][value]']
                                        btp_payment_from_applicable_countries: //select[@name='groups[banktransfer][fields][allowspecific][value]']
                                    multiselects:
                                        btp_payment_from_specific_countries: //select[@name='groups[banktransfer][fields][specificcountry][value][]']
                                    checkboxes:
                                        btp_title_use_default: //input[@name='groups[banktransfer][fields][title][inherit]']
                                        btp_instruction_use_default: //input[@name='groups[banktransfer][fields][instructions][inherit]']
                                        btp_minimum_order_total_use_default: //input[@name='groups[banktransfer][fields][min_order_total][inherit]']
                                        btp_maximum_order_total_use_default: //input[@name='groups[banktransfer][fields][max_order_total][inherit]']
                                        btp_sort_order_use_default: //input[@name='groups[banktransfer][fields][sort_order][inherit]']
                                        btp_enabled_use_default: //input[@name='groups[banktransfer][fields][active][inherit]']
                                        btp_new_order_status_use_default: //input[@name='groups[banktransfer][fields][order_status][inherit]']
                                        btp_payment_from_applicable_countries_use_default: //input[@name='groups[banktransfer][fields][allowspecific][inherit]']
                                        btp_payment_from_specific_countries_use_default: //input[@name='groups[banktransfer][fields][specificcountry][inherit]']
                            -
                                cash_on_delivery_payment:
                                    xpath: //fieldset[@id='payment_cashondelivery']
                                    links:
                                        bank_transfer_payment_link: //parent::div//a[@id='payment_cashondelivery-head']
                                    fields:
                                        cod_title: //input[@name='groups[cashondelivery][fields][title][value]']
                                        cod_instruction: //textarea[@name='groups[cashondelivery][fields][instructions][value]']
                                        cod_minimum_order_total: //input[@name='groups[cashondelivery][fields][min_order_total][value]']
                                        cod_maximum_order_total: //input[@name='groups[cashondelivery][fields][max_order_total][value]']
                                        cod_sort_order: //input[@name='groups[cashondelivery][fields][sort_order][value]']
                                    dropdowns:
                                        cod_enabled: //select[@name='groups[cashondelivery][fields][active][value]']
                                        cod_new_order_status: //select[@name='groups[cashondelivery][fields][order_status][value]']
                                        cod_payment_from_applicable_countries: //select[@name='groups[cashondelivery][fields][allowspecific][value]']
                                    multiselects:
                                        cod_payment_from_specific_countries: //select[@name='groups[cashondelivery][fields][specificcountry][value][]']
                                    checkboxes:
                                        cod_title_use_default: //input[@name='groups[cashondelivery][fields][title][inherit]']
                                        cod_instruction_use_default: //input[@name='groups[cashondelivery][fields][instructions][inherit]']
                                        cod_minimum_order_total_use_default: //input[@name='groups[cashondelivery][fields][min_order_total][inherit]']
                                        cod_maximum_order_total_use_default: //input[@name='groups[cashondelivery][fields][max_order_total][inherit]']
                                        cod_sort_order_use_default: //input[@name='groups[cashondelivery][fields][sort_order][inherit]']
                                        cod_enabled_use_default: //input[@name='groups[cashondelivery][fields][active][inherit]']
                                        cod_new_order_status_use_default: //input[@name='groups[cashondelivery][fields][order_status][inherit]']
                                        cod_payment_from_applicable_countries_use_default: //input[@name='groups[cashondelivery][fields][allowspecific][inherit]']
                                        cod_payment_from_specific_countries_use_default: //input[@name='groups[cashondelivery][fields][specificcountry][inherit]']
                -
                    general_general:
                        fieldsets:
                            -
                                states_options:
                                    xpath: //fieldset[@id='general_region']
                -
                    general_design:
                        fieldsets:
                            -
                                transaction_emails:
                                    xpath: //fieldset[@id='design_email']
                -
                    catalog_rss_feeds:
                        fieldsets:
                            -
                                order_rss:
                                    xpath: //fieldset[@id='rss_order']
                -
                    sales_google_api:
                        fieldsets:
                            -
                                google_shopping:
                                    xpath: //fieldset[@id='google_googleshopping']
                -
                    social_facebook:
                        xpath: //a[contains(@href, 'edit/section/facebook/')]
                        fieldsets:
                            -
                                facebook_config:
                                    xpath: //fieldset[@id='facebook_config']
                -
                    sales_pdf_print_outs:
                        fieldsets:
                            -
                                invoice_pdf:
                                    xpath: //fieldset[@id='sales_pdf_invoice']
                            -
                                shipment_pdf:
                                    xpath: //fieldset[@id='sales_pdf_shipment']
                            -
                                credit_memo_pdf:
                                    xpath: //fieldset[@id='sales_pdf_creditmemo']
                -
                    sales_sales:
                        fieldsets:
                            -
                                minimum_advertised_price:
                                    xpath: //fieldset[@id='sales_msrp']
                -
                    sales_sales_emails:
                        fieldsets:
                            -
                                order_sales:
                                    xpath: //fieldset[@id='sales_email_order']
                            -
                                invoice_sales:
                                    xpath: //fieldset[@id='sales_email_invoice']
                            -
                                shipment_sales:
                                    xpath: //fieldset[@id='sales_email_shipment']
                            -
                                credit_memo_sales:
                                    xpath: //fieldset[@id='sales_email_creditmemo']
                -
                    sales_shipping_methods:
                        fieldsets:
                            -
                                dhl_new:
                                    xpath: //fieldset[@id='carriers_dhlint']
                -
                    services_oauth:
                        xpath: //a[contains(@href, 'edit/section/oauth/')]
                        fieldsets:
                            -
                                email:
                                    xpath: //fieldset[@id='oauth_email']
                            -
                                cleanup_settings:
                                    xpath: //fieldset[@id='oauth_cleanup']
                -
                    customers_customer_configuration:
                        fieldsets:
                            -
                                captcha_customer:
                                    xpath: //fieldset[@id='customer_captcha']
                -
                    customers_wishlist:
                        fieldsets:
                            -
                                general_options_wishlist:
                                    xpath: //fieldset[@id='wishlist_general']
                -
                    customers_persistent_shopping_cart:
                        fieldsets:
                            -
                                general_options_shopping_cart:
                                    xpath: //fieldset[@id='persistent_options']
                -
                    advanced_developer:
                        fieldsets:
                            -
                                image_processing_settings:
                                    xpath: //fieldset[@id='dev_image']
                            -
                                static_files_settings:
                                    xpath: //fieldset[@id='dev_static']
                -
                    advanced_admin:
                        fieldsets:
                            -
                                admin_user_emails:
                                    fields:
                                        recovery_link_exp_period: //input[@name='groups[emails][fields][password_reset_link_expiration_period][value]']
                            -
                                dashboard_admin:
                                    xpath: //fieldset[@id='admin_dashboard']
                            -
                                captcha_admin:
                                    xpath: //fieldset[@id='admin_captcha']
                -
                    general_reports:
                        fieldsets:
                            -
                                dashboard_report:
                                    xpath: //fieldset[@id='reports_dashboard']
                -
                    all_tabs:
                        xpath: //*[@id='system_config_tabs']/li/dl/dd

system_configuration_tabs:
    uimap: *system_configuration_uimap

system_configuration_website:
    uimap: *system_configuration_uimap

system_configuration_store:
    uimap: *system_configuration_uimap

system_configuration_country:
    uimap: *system_configuration_uimap
