#
# {license_notice}
#
# @category    Magento
# @package     Magento
# @subpackage  functional_tests
# @copyright   {copyright}
# @license     {license_link}
#
---
################################################################################
#                                                                              #
#                      Browsers for running tests                              #
#                                                                              #
################################################################################
browsers:
    googlechrome: &googlechrome
         browser: 'Google Chrome'
         browserName: 'chrome'
         host: 'localhost'
         port: 4444
         seleniumServerRequestsTimeout: 60
         sessionStrategy: shared
         desiredCapabilities:
            platform: ANY
    firefox: &firefox
         browser: 'Firefox'
         browserName: 'firefox'
         host: 'localhost'
         port: 4444
         seleniumServerRequestsTimeout: 60
         sessionStrategy: shared
         desiredCapabilities:
            platform: ANY
    iexplorer: &iexplorer
         browser: 'Internet Explorer'
         browserName: 'iexplore'
         host: 'localhost'
         port: 4444
         seleniumServerRequestsTimeout: 60
         sessionStrategy: shared
         desiredCapabilities:
            platform: ANY
    default: *firefox
################################################################################
#                                                                              #
#                     Framework configuration                                  #
#                                                                              #
################################################################################
framework:
    fixture_base_path: 'fixture'
    testsuite_base_path: 'testsuite'
    coverageScriptUrl: ''
    saveScreenshotOnFailure: true
    saveHtmlPageOnFailure: false
    load_all_uimaps: true
    load_all_data: false
    cache:
        frontend:
            name: 'core'
            options:
                caching: false
                cache_id_prefix: 'selenium_'
                automatic_serialization: true
        backend:
            name: 'file'
            options:
                cache_dir: 'var/cache'
################################################################################
#                                                                              #
#                  Applications for running tests                              #
#                                                                              #
################################################################################
applications:
    mage: &mage
        fallbackOrderFixture: 'default'
        fallbackOrderHelper: 'Core'
        ftp: &ftp
            url: 'localhost'
            base_dir: ''
            login: 'admin'
            password: '123123q'
        areas:
            admin:
                url: 'http://www.localhost.com/magento/admin/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: &paypalSandbox
                url: 'https://www.sandbox.paypal.com/'
                base_page_uimap: 'paypal_sandbox'
                uimap_path: 'paypal_sandbox'
                login: 'paypal_sandbox_login'
                password: 'paypal_sandbox_password'
            paypal_developer: &paypalDeveloper
                url: 'https://developer.paypal.com/'
                base_page_uimap: 'paypal_developer_home'
                uimap_path: 'paypal_developer'
                login: 'paypal_developer_login'
                password: 'paypal_developer_password'
    community17: &ce17
         fallbackOrderFixture: 'community17, default'
         fallbackOrderHelper: 'Community17, Core'
         ftp: *ftp
         areas:
            admin:
                url: 'http://www.localhost.com/magento17_community/control/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento17_community/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    community1701: &ce1701
        fallbackOrderFixture: 'community1701, community17, default'
        fallbackOrderHelper: 'Community1701, Community17, Core'
        ftp: *ftp
        areas:
            admin:
                url: 'http://www.localhost.com/magento_community1701/control/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento_community1701/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    enterprise112: &ee112
        fallbackOrderFixture: 'enterprise, default'
        fallbackOrderHelper: 'Enterprise, Core'
        ftp: *ftp
        areas:
            admin:
                url: 'http://www.localhost.com/magento_enterprise1200/admin/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento_enterprise1200/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    enterprise11201: &ee11201
        fallbackOrderFixture: 'enterprise11201, enterprise, default'
        fallbackOrderHelper: 'Enterprise11201, Enterprise, Core'
        ftp: *ftp
        areas:
            admin:
                url: 'http://www.localhost.com/magento_enterprise1201/control/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento_enterprise1201/control/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    magento2community: &m2ce
        fallbackOrderFixture: 'community2, community17, default'
        fallbackOrderHelper: 'Community2, Community17, Core'
        ftp: *ftp
        areas:
            admin:
                url: 'http://www.localhost.com/magento2_community/control/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento2_community/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    magento2enterprise: &m2ee
        fallbackOrderFixture: 'enterprise2, enterprise, default'
        fallbackOrderHelper: 'Enterprise2, Enterprise, Core'
        ftp: *ftp
        areas:
            admin:
                url: 'http://www.localhost.com/magento2_enterprise/control/'
                url: 'http://www.localhost.com/magento_2enterprise/control/'
                base_page_uimap: 'log_in_to_admin'
                uimap_path: 'admin'
                login: 'admin'
                password: '123123q'
            frontend:
                url: 'http://www.localhost.com/magento2_enterprise/'
                base_page_uimap: 'home_page'
                uimap_path: 'frontend'
            paypal_sandbox: *paypalSandbox
            paypal_developer: *paypalDeveloper
    default: *m2ce
