#
#
# {license_notice}
#
# @category    Magento
# @package     Magento
# @subpackage  functional_tests
# @copyright   {copyright}
# @license     {license_link}
#
---
#
product_page:
    uimap:
        form:
            fieldsets:
                -
                    customize_product_info:
                        xpath: //div[@id='options-container']
                        links:
                            customized_add_to_wishlist: //a[text()='Add to Wishlist']
                -
                    product_info:
                        buttons:
                            customize_and_add_to_cart: //button[span='Customize and Add to Cart']
                        pageelements:
                            qty: /..//input[@class='input-text qty'][@value='%price%']
                -
                    add_tag:
                        buttons:
                            add_tags: //button[//span='Add Tags']
                -
                    details:
                        xpath: //div[dl/dt/span='Details']

product_review:
    uimap:
        form:
            fieldsets:
                -
                    customize_product_info:
                        xpath: //div[@id='options-container']
                -
                    product_info:
                        buttons:
                            customize_and_add_to_cart: //button[span='Customize and Add to Cart']
                -
                    customer_reviews:
                        pageelements:
                            review_reviewer_name: //dt[contains(.,'%reviewerName%')]
                            review_details: //dt[contains(.,'%reviewerName%')]/following-sibling::dd[1]
                            review_details_ratings: //dt[contains(.,'%reviewerName%')]/following-sibling::dd[1]/table
                            review_details_ratings_line: //dt[contains(.,'%reviewerName%')]/following-sibling::dd[1]/table//th
                            review_post_date: //dt[contains(.,'%reviewerName%')]/following-sibling::dd[1]/p[2]
                        links:
                            review_summary: //dt[contains(.,'%reviewerName%')]/a
